/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FamilyMember = IDL.Variant({
  'nik' : IDL.Null,
  'mariana' : IDL.Null,
  'marina' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : FamilyMember,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'familyMember' : IDL.Opt(FamilyMember),
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'sender' : FamilyMember,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([MessageInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FamilyMember = IDL.Variant({
    'nik' : IDL.Null,
    'mariana' : IDL.Null,
    'marina' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : FamilyMember,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'familyMember' : IDL.Opt(FamilyMember),
  });
  const MessageInput = IDL.Record({
    'content' : IDL.Text,
    'sender' : FamilyMember,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([MessageInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };